import java.util.*;
//Question: Given an positive integer array, print the min number generated by
//concating all numbers in the aray.





//Answer: First use a comparator which gives a < b when a+""+b < b+""+a, then concat all numbers
//in that order.
//Proof: case1 abxxx < baxxx;
//       case2 xxxab < xxxba;
//       case3 ay < ya, yb < by => ayb < yab < yba < bya => ayb < bya;
public class Solution {
    public String PrintMinNumber(int [] numbers) {
        if(numbers == null || numbers.length == 0) return "";
        int len = numbers.length;
        String[] str = new String[len];
        StringBuilder sb = new StringBuilder();
        for(int i = 0; i < len; i++){
            str[i] = String.valueOf(numbers[i]);
        }
        Arrays.sort(str,new Comparator<String>(){
            @Override
            public int compare(String s1, String s2) {
                String c1 = s1 + s2;
                String c2 = s2 + s1;
                return c1.compareTo(c2);
            }
        });
        for(int i = 0; i < len; i++){
            sb.append(str[i]);
        }
        return sb.toString();
    }
}
